### ISSUE TITLE
FYI: Your plugin has been added to Awesome Kustomize

### ISSUE THREAD

**Issue by aabouzaid** [openinfradev/kustomize-helm-transformer#32]
Hi :wave: 

I just started an [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/#transformers) :tada:
Because after using Kustomize for 3 years, there was no central place for Kustomize resources.

I've found your repo via GitHub labels, and I find it totally helpful.

Thank you :rocket:

**Comment by bluejayA** [comment]
Thanks @aabouzaid. Let me know if you need more information on how and why we use it.

**Comment by aabouzaid** [comment]
@bluejayA Thank you :+1: 
I'd say your repo is pretty clear. But in general, more docs increase the users' adoption.

Also maybe you want to consider adding **KRM functions** support since the old plugin methods (exec and go plugin) are [deprecated](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#plugin-feature-status).

Here is an example of [adding KRM support in SopsSecretGenerator](https://github.com/goabout/kustomize-sopssecretgenerator/pull/32). It's pretty easy.

Feel free to close this issue anytime :rocket:
